model_name: "policy_2026-04-10_21-14-55.pt"
framework: "isaacsim"
rows: 4
cols: 4
decimation: 4
num_observations: 57
observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
# observations_history: [0]
observations_history: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
clip_obs: 60.0
clip_actions_lower: [-60, -60, -60, -60,
                     -60, -60, -60, -60,
                     -60, -60, -60, -60,
                     -60, -60, -60, -60]
clip_actions_upper: [60, 60, 60, 60,
                     60, 60, 60, 60,
                     60, 60, 60, 60,
                     60, 60, 60, 60]

# clip_actions_lower: [-45, -45, -45,
#                      -45, -45, -45,
#                      -45, -45, -45,
#                      -45, -45, -45]
# clip_actions_upper: [45, 45, 45,
#                      45, 45, 45,
#                      45, 45, 45,
#                      45, 45, 45]
                     
# rl_kp: [45, 45, 45, 45,
#         50, 50, 50, 50,
#         60, 60, 60, 60,
#         1000, 1000, 1000, 1000]

rl_kp: [50, 55, 65, 2,
        50, 55, 65, 2,
        50, 55, 65, 2,
        50, 55, 65, 2]

# rl_kd: [1.5, 1.5, 1.5, 1.5,
#         1.5, 1.5, 1.5, 1.5,
#         2.0, 2.0, 2.0, 2.0,
#         10.0, 10.0, 10.0, 10.0]

rl_kd: [1.5, 1.5, 2.5, 2.5,
        1.5, 1.5, 2.5, 2.5,
        1.5, 1.5, 2.5, 3.0,
        1.5, 1.5, 2.5, 3.0]
hip_scale_reduction: 1.0
hip_scale_reduction_indices: [0, 4, 8, 12]
num_of_dofs: 16
# action_scale: 0.25
action_scale: [0.1, 0.1, 0.1, 0.02,
               0.1, 0.1, 0.1, 0.02,
               0.1, 0.1, 0.1, 0.02,
               0.1, 0.1, 0.1, 0.02]

lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05

commands_scale: [1.0, 1.0, 1.0]

torque_limits: [40.0, 40.0, 40.0, 40,
                40.0, 40.0, 40.0, 40,
                40.0, 40.0, 40.0, 40,
                40.0, 40.0, 40.0, 40]